### ISSUE TITLE
Dynamips not working/Works only on New York Time zone

### ISSUE THREAD

**Issue by leribe** [GNS3/dynamips#100]
Hi Guys, 
can you please help, have upgraded to gns3 2.2.0 and can't start routers, however works well if i use new york time zone, had the same issue on 2.1 and worked well, please assist, error below.

Dynamips hypervisor process has stopped, return code: -11
C7200 'Ghost': generic_nvram_extract_config: Unknown error -61605

**Comment by grossmj** [comment]
I thought we fixed this already. What version of Dynamips do you run?

**Comment by leribe** [comment]
Yes, i can remeber being fixed on 2.1.0, can't get dynamips -v, please see below, hopefully helpfull, thanks Sir.
Cisco Router Simulation Platform (version 0.2.18-amd64/Linux stable)
Copyright (c) 2005-2011 Christophe Fillot.
Build date: Apr  3 2018 09:35:00

**Comment by grossmj** [comment]
How have you installed Dynamips? Version 0.2.21 fixes this issue: https://github.com/GNS3/dynamips/releases/tag/v0.2.21

**Comment by leribe** [comment]
Thank you, working.
Installed from repo, please update repo if not updated with latest dynamips.
