### ISSUE TITLE
Use of uninitialized variable

### ISSUE THREAD

**Issue by ash1852** [GNS3/dynamips#125]
hello, I found a bug of use of uninitialized variable in the source code of dynamips , would you help me check if this bug is true?Thank you very much!
here is an overview of bug occurrence.
<img width="837" alt="1" src="https://user-images.githubusercontent.com/87304478/145379491-6e996e43-558d-4c40-96b2-816c6b420737.png">
**step1:**
in file dynamips/common/rom2c.c , [line 100](https://github.com/GNS3/dynamips/blob/master/common/gen_eth.c#L100):
call **pcap_next** and use its return value to compare with **pkt_ptr**
**step2:**
in file libpcap-1.8.1/pcap.c, line 238:
**pkt** is declared here bug uninitialized.
**step3:**
in file libpcap-1.8.1/pcap.c, line 245:
return uninitialized pointer **pkt**
**step4**:
in file dynamips/common/rom2c.c , [line 100](https://github.com/GNS3/dynamips/blob/master/common/gen_eth.c#L100):
return value of pcap_next  is used in the compare operation but  not initialized

**Comment by ash1852** [comment]
additionally, there is also a bug of use of uninitialized if the bug above is true. they can be fixed together.
<img width="839" alt="2" src="https://user-images.githubusercontent.com/87304478/145387569-9327c09f-c86d-4f74-8fb2-97244cfb7638.png">
thanks for your patience and effort.

**Comment by flaviojs** [comment]
Not a bug. `pcap_next` calls `pcap_dispatch`, which updates pkt.
`pkt` has whatever packet came before.
