### ISSUE TITLE
Null pointer dereference

### ISSUE THREAD

**Issue by ash1852** [GNS3/dynamips#126]
hello, I found a bug of null-pointer-dereference in the source code of dynamips , would you help me check if this bug is true?Thank you very much!
here is an overview of bug occurrence.
![image](https://user-images.githubusercontent.com/87304478/145395640-e924740c-f1c6-49f8-888e-fa41eb88596c.png)
**step1**:
in file dynamips/common/rom2c.c, [line 63](https://github.com/GNS3/dynamips/blob/master/common/rom2c.c#L63):
call **elf32_getehdr** and load its return value to **ehdr**(addtionally,**img_elf** is guaranteed not to be null according to [line 46](https://github.com/GNS3/dynamips/blob/master/common/rom2c.c#L46))
![image](https://user-images.githubusercontent.com/87304478/145397596-6c826aca-3510-45ee-bb24-5ae8ac1bd9a7.png)

**step2**:
in file libelf/elf32_getehdr.c, line 92:
call **getehdr_impl**, **img_elf** is used as the 1st parameter
![image](https://user-images.githubusercontent.com/87304478/145397712-aecb8e41-e308-490e-b227-42a0c458c4fe.png)

**step3**:
in file libelf/elf32_getehdr.c, line 53/71:
there are two paths that may return **null**(though with low possibility)
![image](https://user-images.githubusercontent.com/87304478/145397830-6b755527-f510-4931-b070-77bdd9ceb73b.png)

**step4**:
in file libelf/elf32_getehdr.c, line 95:
return **result** to caller which can be **null**
![image](https://user-images.githubusercontent.com/87304478/145397861-044e2162-5e84-49e3-aebd-228a67862f5c.png)

**step5**:
in file dynamips/common/rom2c.c, [line 63](https://github.com/GNS3/dynamips/blob/master/common/rom2c.c#L63):
load return value of **elf32_getehdr** to ehdr which can be **null**
![image](https://user-images.githubusercontent.com/87304478/145397596-6c826aca-3510-45ee-bb24-5ae8ac1bd9a7.png)
step6:
in file dynamips/common/rom2c.c, [line 74](https://github.com/GNS3/dynamips/blob/master/common/rom2c.c#L74):
derefer **ehdr** without check if **ehdr** is **null**
![image](https://user-images.githubusercontent.com/87304478/145397937-c6b3472d-e855-4187-a212-8322450972fb.png)

**Comment by ash1852** [comment]
is this bug is true? or false.looking forward to your reply.

**Comment by flaviojs** [comment]
Not a bug.
Passing the `elf32_getphdr` check before that code guarantees that this path is not taken.
