### ISSUE TITLE
GNS3 dynamips crash after Ubuntu upgrade to 22.04.LTS

### ISSUE THREAD

**Issue by medharrak** [GNS3/dynamips#128]
Ubuntu 22.04 LTS 

Kernel 5.15.0-25-generic

GNS3: 2.2.31

$ gdb -c /var/crash/_usr_bin_dynamips.0.crash /usr/bin/dynamips
GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/dynamips...
(No debugging symbols found in /usr/bin/dynamips)
/var/crash/_usr_bin_dynamips.0.crash: Permission denied.
(gdb) bt
No stack.

----------------

Node log for c3745_i1_log.txt:

Apr 28 08:47:17.901 VTTY: Console port: waiting connection on tcp port 5009 for protocol IPv4 (FD 8)
Apr 28 08:47:17.907 slot0: C/H/S settings = 0/4/32
Apr 28 08:47:17.907 slot1: C/H/S settings = 0/4/32
Apr 28 08:47:18.113 C3745_BOOT: starting instance (CPU0 PC=0xffffffffbfc00000,idle_pc=0x603c6160,JIT on)
Apr 28 08:47:18.113 CPU0: CPU_STATE: Starting CPU (old state=2)...

**Comment by DresslerFrank** [comment]
Compile with `CFLAGS="-mstackrealign" cmake ..` for a quick fix. #129 fixes it properly

**Comment by grossmj** [comment]
Fixed by #129
