### ISSUE TITLE
v0.2.23: Console port is opened on 127.0.0.1 instead of 0.0.0.0 by default

### ISSUE THREAD

**Issue by brownhami** [GNS3/dynamips#138]
In previous versions, the console port would always be opened on 0.0.0.0, so that the console could be accessed via any IP.
Now the console incorrectly binds to 127.0.0.1 instead meaning that the console can only be accessed by processes running on the same machine as the dynamips process.

This breaks console functionality for Cisco devices running on remote GNS3 servers as the console cannot be accessed remotely any more.

**Comment by grossmj** [comment]
We changed that for security reasons however you can force Dynamips to listen on 0.0.0.0 for consoles.

Tick the "Allow console connections to any local IP address" option in the preferences

![Screenshot from 2023-09-12 16-28-39](https://github.com/GNS3/dynamips/assets/4752614/b251bc76-9459-4f19-a75b-1f696def96ed)

or manually start the GNS3 server with the `--allow` parameter: `gns3server --local --allow`

**Comment by grossmj** [comment]
@brownhami does this fix your problem?
