### ISSUE TITLE
Unable to define port adapter

### ISSUE THREAD

**Issue by blackbit42** [GNS3/dynamips#139]
I am using dynamips v0.2.23 on Debian amd64. Dynamips is built from source as the version supplied by Debian is pretty old (0.2.14), though observed behavior is consistent across versions.

My quest is to run dynamips standalone, i.e. without GNS3, with an IOSnetwork interface hooked onto a host OS tap interface.
Based on instructions in the manpage I've crafted my commandline like this:

```
sudo dynamips \
        -i R1 \
        -X \
        --idle-pc=0x62f21aa4 \
        -p 0:C7200‐IO‐FE \
        -s 0:0:tap:tap3 \
        ../<image file>
```

The port adapter I am attempting to use seems to be available in principle, there is no mention of `(NOT WORKING)`.
```
$ dynamips 2>/dev/null | grep C7200-IO-FE
  * C7200-IO-FE 
$
```

Though, unfortunately, dynamips fails to work with the `-p` and `-s` directives I provide.
```
C7200 'default': unknown card type 'C7200‐IO‐FE' for slot 0/0.
C7200 'default': unable to add NETIO binding for slot 0
```

I struggle to understand if my syntax is incorrect, the error message is misleading or something else is off.

What am I doing wrong here?

**Comment by blackbit42** [comment]
It turns out, the string `C7200-IO-FE` I had in the shell script that starts dynamips was UTF-8 encoded, which confuses dynamips. Converting that to ASCII resolved the issue.

**Comment by grossmj** [comment]
@blackbit42 Have you solved your own issue? Sorry I haven't replied earlier. I always use Dynamips in hypervisor mode so I never add the problem you faced.

**Comment by blackbit42** [comment]
Yes, I was able to solve it myself.

The situation was misleading. By looking at the error message I got the impression that dynamips is saying a card type isn't known that is reported as being available. For whatever reason a UTF-encoded string ended up in the shell script I am using.
