### ISSUE TITLE
compile in MinGW

### ISSUE THREAD

**Issue by flaviojs** [GNS3/dynamips#18]
dynamips doesn't compile in MinGW.
Currently it can compile in Cygwin by relying on it's posix-ness.

Tasks:
- lock files
  
  use https://github.com/epi/xedisk/wiki/File-locking as reference
- missing header `sys/mmap.h`
  
  memory mapped files, can be replaced with `windows.h` (WinXP+)
  
  [mmap](http://linux.die.net/man/2/mmap) -> [CreateFileMapping](http://msdn.microsoft.com/en-us/library/windows/desktop/aa366537.aspx) + [MapViewOfFile](http://msdn.microsoft.com/en-us/library/windows/desktop/aa366761.aspx)
  
  [munmap](http://linux.die.net/man/2/munmap) -> [UnmapViewOfFile](http://msdn.microsoft.com/en-us/library/windows/desktop/aa366882.aspx)
  
  [msync](http://linux.die.net/man/2/msync)  -> [FlushViewOfFile](http://msdn.microsoft.com/en-us/library/windows/desktop/aa366563.aspx) (asynchronous, so not exactly what we need)
  
  consider moving `memzone_*` functions from `utils.c` to a separate file `memzone.c`
- missing header `uuid/uuid.h`
  
  external library, can be replaced with `Rpc.h` (Win2000+)
  
  create compatible functions
  
  uuid_t <-> [UUID](http://msdn.microsoft.com/en-us/library/windows/desktop/aa379358.aspx) - convert Data1 with `htonl/ntohl`, convert Data2 and Data3 with `htons/ntohs`
  
  [uuid_generate](http://linux.die.net/man/3/uuid_generate) -> [UuidCreateNil](http://msdn.microsoft.com/en-us/library/windows/desktop/aa379262.aspx) + [UuidCreate](http://msdn.microsoft.com/en-us/library/windows/desktop/aa379205.aspx)
  
  [uuid_parse](http://linux.die.net/man/3/uuid_parse) -> [UuidFromString](http://msdn.microsoft.com/en-us/library/windows/desktop/aa379336.aspx)
  
  [uuid_unparse](http://linux.die.net/man/3/uuid_unparse) -> [UuidToString](http://msdn.microsoft.com/en-us/library/windows/desktop/aa379352.aspx)
  
  [uuid_compare](http://linux.die.net/man/3/uuid_compare) -> [UuidCompare](http://msdn.microsoft.com/en-us/library/windows/desktop/aa379201.aspx)
- missing headers `sys/socket.h` + `sys/un.h` + `arpa/inet.h` + `netdb.h` + `netinet/in.h`
  
  sockets, can be replaced with `winsock2.h` + `ws2tcpip.h` (WinXP+ or WinVista+)
  
  most IPv6 stuff is WinVista+, ~~try to implement it for WinXP+?~~ (WinXP is EOL now)
  
  `struct sockaddr_un` doesn't exist, filter out code that needs it
- other missing headers
  
  ~~`arpa/inet.h` - dev_vtty.c, gen_eth.c, hv_atmsw.c, hv_atm_bridge.c, hv_c1700.c, hv_c2600.c, hv_c2691.c, hv_c3600.c, hv_c3725.c, hv_c3745.c, hv_c7200.c, hv_ethsw.c, hv_frsw.c, hv_nio.c, hv_nio_bridge.c, hv_store.c, hv_vm_debug.c, net.c, net_io.c, net_io_filter.c, parser.c, timer.c, utils.c, hv_vm.c, hypervisor.c~~
  `arpa/telnet.h`\- dev_vtty.c
  `dlfcn.h` - plugin.c
  ~~`netdb.h` - dev_vtty.c, gen_eth.c, net.c, net_io.c, net_io_filter.c, timer.c, utils.c~~
  ~~`netinet/in.h` - gen_eth.c, net_io.c, net_io_filter.c, timer.c, utils.h(!!)~~
  `netinet/tcp.h` - dev_vtty.c
  `sys/ioctl.h` - gen_eth.c, hv_atmsw.c, hv_atm_bridge.c, hv_c1700.c, hv_c2600.c, hv_c2691.c, hv_c3600.c, hv_c3725.c, hv_c3745.c, hv_c7200.c, hv_ethsw.c, hv_frsw.c, hv_nio.c, hv_nio_bridge.c, hv_store.c, hv_vm_debug.c, net.c, net_io.c, net_io_filter.c, parser.c, utils.c, hv_vm.c, hypervisor.c
  ~~`sys/mman.h` - utils.c~~
  `sys/select.h` - atm.c, atm_bridge.c, atm_vsar.c, eth_switch.c, frame_relay.c, net_io_bridge.c
  ~~`sys/socket.h` - cisco_eeprom.c, dev_vtty.c, gen_eth.c, hv_atmsw.c, hv_atm_bridge.c, hv_c1700.c, hv_c2600.c, hv_c2691.c, hv_c3600.c, hv_c3725.c, hv_c3745.c, hv_c7200.c, hv_ethsw.c, hv_frsw.c, hv_nio.c, hv_nio_bridge.c, hv_store.c, hv_vm_debug.c, net.c, net_io.c, net_io.h(!!), net_io_filter.c, net_io_filter.h(!!), parser.c, ptask.h(!!), timer.c, utils.c, hv_vm.c, hypervisor.c~~
  `sys/uio.h` - atm_vsar.c
  ~~`sys/un.h` - net_io.c, net_io.h(!!), net_io_filter.c, net_io_filter.h(!!), ptask.h(!!)~~
  `sys/wait.h` - gen_eth.c, net_io.c, net_io_filter.c, registry.c
  `termios.h` - dev_c1700_iofpga.c, dev_c2600_iofpga.c, dev_c2691_iofpga.c, dev_c3600_iofpga.c, dev_c3725_iofpga.c, dev_c3745_iofpga.c, dev_c6msfc1_iofpga.c, dev_c6sup1_iofpga.c, dev_c7200_iofpga.c, dev_ds1620.c, dev_ns16552.c, dev_sb1.c, dev_sb1_io.c, dev_vtty.c
- consider adding a global include, like `all.h`, to be included before anything else.
  
  all OS/compiler juggling can be put in there, as well as common includes.
  
  currently `utils.h` serves that purpose, along with providing utility functions.
- check all `long`s
  
  in windows it's always 32-bits, in linux it's either 32-bits or 64-bits (size of pointer)
- find more stuff that needs changing...
- ~~make it compile with CMake (optional)~~ - cmake is supported now

**Comment by hertzsprung** [comment]
I just tried compiling an application that includes uuid/uuid.h and x86_64-w64-mingw32-gcc complains that "uuid/uuid.h": No such file or directory.  Is this because libuuid(3) isn't supported by mingw?  Is this likely to be added in the near future?

**Comment by neozeed** [comment]
I have it building on MinGW.  Oddly enough the 'stable' branch runs the MIPS64 JIT quite nicely, while the unstable branch runs the PPC32 JIT.  Libuuid will conflict with windows built in uuid support so the fix there is it rename libuuid's uuid_t to something like uu_uuid_t and all references to it in Dynamips.  Of course, don't forget to rename the library file, otherwise you'll overwrite the system libuuid.a !

There is some stuff to mess around with sockets in the hypervisor, as Win32 can't treat a socket like a stdio device, but I have it to the point where dynagen 0.11 can talk to dynamips.

I put my stuff here:
http://sourceforge.net/projects/dynamips-mingw/

Also I have it compiling with TDM-GCC-64, although none of the JIT works.  But it does work interpreted!

**Comment by grossmj** [comment]
@neozeed we have recently remove the libuuid dependency. Have you made progress?

**Comment by neozeed** [comment]
I never had issues once I renamed uuid to uu_uuid.  But now that I see it's updated, I can pull and re-merge my stuff.

**Comment by grossmj** [comment]
Sounds good, let me know how that goes.

Thanks :)

**Comment by neozeed** [comment]
I've got a first pass.... [and I still ended up cutting it in half](https://sourceforge.net/projects/dynamips-mingw/files/dynamips-github/dynamips-mingw-build1-github-0.2.16.7z/download), MIPS from stable, and PowerPC from unstable.  Both seem to be somewhat behaved.  I've booted 7200 MIPS, and 1700 PPC IOS ok.  The pcap code needs to be made more dynamic for UNIX.  I've done it before, I just have to find it and put it in there.

I've separated all the bits that are missing from MinGW into the contrib folder.

Also I've been going in circles on the vty code, so for now Im just using an older version of that file.  It works 'well enough for now'.  Just go into the 'merge' directory and run make, as it's all MinGW32.  I guess I should rename merge to mingw..

**Comment by grossmj** [comment]
Looks like you did a good job :+1: I will be away for the next couple of week, so I won't be able to test before a while. I will post back when I do.

Thanks again! :)

**Comment by neozeed** [comment]
I forgot, I had to make the unix & vde transports optional as a #ifdef UNIX_ETH & VDE_ETH since Win32 has no good analogue.

**Comment by noplay** [comment]
Awesome

**Comment by neozeed** [comment]
I really really need to revisit all of this. You know how live (new kids) and overwhelming jobs go. :|

On a long trip I was reading that book infrastructure as code, and Ive been trying to get to that point for years but it's nice to see it just spelt out.  And time to re-tackle dynamips.

**Comment by grossmj** [comment]
No worries. I am very interested for a version of Dynamips compiled with
MinGW.
