### ISSUE TITLE
Idle-pc values forgotten after Router restart

### ISSUE THREAD

**Issue by Technologov** [GNS3/dynamips#57]
Hi,

I have a c7200 + IOS 15.2, and when I apply idle-PC it works, until I restart the router.
After that, it uses 100% CPU.

IOS image = c7200-adventerprisek9-mz.152-4.S5.bin
Dynamips 0.2.14. for Windows.

-Technologov

**Comment by Technologov** [comment]
This is a _HUGE_ problem, and disallows me to work with multiple routers on my PC. Plus it happens with 12.4 and 15.0/15.1 IOSes also.

**Comment by jimdigriz** [comment]
Are you using the compressed `.bin`?  I could not find this wisdom in the documentation but did in some  random forum posts, the idle PC is stable (plus it also boots faster) if you extract the actual image and run dynamips against that (then `dynamips --idle-pc=0x62cbf334 C7200-AD.BIN` works):
````
unzip /root/c7200-advipservicesk9-mz.152-4.S5.bin C7200-AD.BIN
````

This partly makes sense as the decompression could (no reason though why it should though) jiggle the PC to a different location in RAM.  If it is already uncompressed, execution is in place and the PC is always in a fixed location.

**Comment by noplay** [comment]
GNS3 also extract the .bin
