### ISSUE TITLE
source of the microcode is unknown/missing

### ISSUE THREAD

**Issue by flaviojs** [GNS3/dynamips#7]
I don't know the source of the microcode.
The oldest dynamips source code I could find already has it in binary form.

**Comment by neozeed** [comment]
Do you think it's based on (oddly written around the same time) as CILO, the linux loader for Cisco 3600/7200/1700 platforms?

All I can find left is this:
http://git.bocc.de/git/gitweb.cgi?p=cilo.git;a=summary

**Comment by andrewshadura** [comment]
@flaviojs, have you had any progress on this since 2014?

**Comment by grossmj** [comment]
@andrewshadura unfortunately we haven't had any contact with @flaviojs for many years now.
