### ISSUE TITLE
Error: Dynamips hypervisor process has stopped, return code: -7

### ISSUE THREAD

**Issue by blomstertj** [GNS3/dynamips#77]
I am using GNS3 1.5.2 Linux (64-bit) with Python 3.5.2 Qt 5.5.1 on Ubuntu 16.04.1

This issue keeps happening on my desktop.  It seems to be random, CPU load low too.  I'll be working on a lab and boom two routers go down.  I've tried setting up via the GNS3 VM in VirtualBox and plain Local Server.  My laptop is running the exact same version of GNS3 and the same operating system and it does not experience this problem. 

This is very frustrating can anyone help? I've reinstalled GNS3 and related packages multiple times and purged their configuration files as well.

**Comment by noplay** [comment]
Are you using a recommended images?
https://gns3.com/support/docs/virtual-machines-supported-2

**Comment by grossmj** [comment]
Yep looks like the IOS image you have used made Dynamips crash.

**Comment by blomstertj** [comment]
I'm using C7200 routers with this image: c7200-adventerprisek9-mz.151-4.M
I got the crash on my laptop as well so it's not just computer independent.  Loading up this topology in GNS3 on Windows 10 on the laptop with the same IOS image and same routers it does not crash.  100% stable.  Why am I having these problems in Linux?

**Comment by noplay** [comment]
Recent OS are less tolerant to faulty memory access, that why it could failed with a image even if the image was working previously.

**Comment by blomstertj** [comment]
is there a way to fix that? Are you saying my image might a corrupt?⁣​

**Comment by noplay** [comment]
Dynamips is a reverse engineering of Cisco hardware. It's possible that the image you have run on hardware different of the hardware reverse engineered by the developers and that could create the crash. In the past Linux allowed you to access to this memory but with recent changes like randomisation of the memory this kind of fault is no longer allowed.

Our recommendation is to use one of the recommended images.

**Comment by blomstertj** [comment]
But the recommended images are copyright protected by Cisco. I'm not really sure what you mean. ⁣​

**Comment by blomstertj** [comment]
Oh I see, I'm looking at them right now.⁣​

**Comment by blomstertj** [comment]
I've tried another IOS image.  I don't think I can get IOS 15 to work correctly.  I may have to use an older router chassis.
