### ISSUE TITLE
Idle-PC value of 0xffffffffc0000000 on all images

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/dynamips#85]
From community forum:
https://gns3.com/qa/idle-pc-value-of-0xffffffffc0000

--------------
I'm just starting to dive into GNS3 so forgive me if this is a common issue. I've searched to the best of my ability, finding no answers specific to my issue.
 
The machine I have GNS3 installed on is running Ubuntu 16.04. It is running on the physical hardware, not in a virtual environment. From my understanding, running a VM isn't really needed when you're in a linux environment as the whole point of the GNS3 VM is to put it in a linux environment. Correct me if I'm wrong.
 
Anyways I have all the appropriate images that are compatible with GNS3 but whenever I go to compute the Idle-PC value, it spits out "0xffffffffc0000000" and then proceeds to tell me it's not a working value when I try to proceed. Now I can go here and find the correct values and use them. Everything seems to work fine when I do so. The only issue left is when I want to make an EtherSwitch out of a device. The same values don't work appropriately when using the device as an EtherSwitch it seems because one of my CPU threads almost immediately maxes out and stays there.
 
Any suggestions?

**Comment by grossmj** [comment]
Best Idle-PC values are obtained when IOS is in idle state, after the "Press RETURN to get started" message has appeared on the console, messages have finished displaying on the console and you have have actually pressed the RETURN key.

Finding the right idle-pc value is a trial and error process, consisting of applying different Idle-PC values and monitoring the CPU usage.

**Comment by fsnyder1** [comment]
I'm the original poster. Your reply is good insight into the Idle-PC value but I'm still left scratching my head on how to counter this issue. I thought the point of the Idle-PC value finder was to find this value or something that at least had potential.

**Comment by ehlers** [comment]
See issue "Auto Idle-PC doesn't work in preference" https://github.com/GNS3/gns3-gui/issues/2344. should be fixed in 2.1.1 (as soon as it's published)

**Comment by mys96169** [comment]
I have this problem too,Could anyone help me?

**Comment by grossmj** [comment]
This should have been fixed. Please use the latest version of GNS3.
