### ISSUE TITLE
Reproducable crash

### ISSUE THREAD

**Issue by ikiris** [GNS3/dynamips#9]
Have a dynamips reproducable crash using self compiled RC7 x86_64 on linux.

session crashes when only running single 7200 npe400 router through GNS3.

Router acting as mpls PE for serial interface pseudowire connection. Trigger for crash is frame relay client off of router establishing a md5 secured eigrp session with the other end frame relay device across the pseudowire.

Pseudowire terminates on a real 7200 physical serial interface on the far end.

How can I assist further?

**Comment by amitdongre** [comment]
You have to add GNS3 folder in C drive to Antivirus Exeption process.

**Comment by noplay** [comment]
AVG create trouble with cygwin application...

**Comment by dwbfox** [comment]
Still seeing this error:
```bash
Jul 01 04:39:48 gns3 kernel: do_general_protection: 2 callbacks suppressed
Jul 01 04:39:48 gns3 kernel: traps: dynamips[1754] general protection ip:7f4c68c284d6 sp:7f4c6184c118 error:0 in libc-2.27.so[7f4c68bbd000+1e7000]
Jul 01 04:39:48 gns3 kernel: traps: dynamips[1756] general protection ip:7f3e49d1f4d6 sp:7f3e42539118 error:0 in libc-2.27.so[7f3e49cb4000+1e7000]

```

```bash
gns3@gns3:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic
```

```bash
gns3@gns3:~/dynamips$ dynamips --help
Cisco Router Simulation Platform (version 0.2.18-amd64/Linux stable)
Copyright (c) 2005-2011 Christophe Fillot.
Build date: Jul  1 2018 03:32:05
```

Any ideas?
