### ISSUE TITLE
Dynamips crashes during file transfer from VM to external computer

### ISSUE THREAD

**Issue by andersonreloaded** [GNS3/dynamips#92]
Hi Folks,
 
We are using GNS3 with simple topology consisting of VirtualBox VMs connected through Ethernet Switch. Ethernet switch is connected to external network through clould over trunk pork. Latest versions of GNS3 and VirtualBox are being used, while Dynamips 32-bit version is running on Ubuntu 18.04.
 
The network is up and running, however when doing file transfer using SCP from external computer to VirtualBox VM, we observed that VM becomes unreachable as Dynamips is crashing. Even a simple ssh login to external computer from VM and running 'ls -lt' command is resulting in similar behaviour. Dynamips logs reveal *** stack smashing *** and hence leading to crash.
 
Is it normal or any special configuration is required to make it work.
 
Thanks!
Neo.

**Comment by flaviojs** [comment]
The stack was probably smashed by a bad function call generated with x86 jit code.
This is probably fixed with #265.
