### ISSUE TITLE
FTBFS: ./getopt.h:53:5: error: conflicting types for ‘getopt’

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/dynamips#94]
Ubuntu 19.04 disco
dynamips v0.6.1-34-gc56569b
gcc 8.2.0-2ubuntu2

Building dynamips with ```cmake .; make``` leads to:
```
gcc -O2 -m64  -DLinux -Di386 -DHV -Wall -I. -DTAP -c hv.c
In file included from hv.c:45:
./getopt.h:53:5: error: conflicting types for ‘getopt’
 int getopt(int argc, char** argv, char* optstr);
     ^~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/getopt_posix.h:27,
                 from /usr/include/unistd.h:869,
                 from hv.c:33:
/usr/include/x86_64-linux-gnu/bits/getopt_core.h:91:12: note: previous declaration of ‘getopt’ was here
 extern int getopt (int ___argc, char *const *___argv, const char *__shortopts)
            ^~~~~~
make: *** [Makefile.linux:38: hv.o] Error 1
```

[dynamips_v0.6.1-34-gc56569b+19.04_amd64.build.log](https://github.com/GNS3/dynamips/files/2893241/dynamips_v0.6.1-34-gc56569b%2B19.04_amd64.build.log)

**Comment by grossmj** [comment]
Do you have the error with an older version of Dynamips?https://github.com/GNS3/dynamips/releases/tag/v0.2.18 for instance

Thanks

**Comment by jean-christophe-manciot** [comment]
I was able to correctly compile & build in the same environment (maybe with slightly older gcc releases):
- 2b08d40 (20180331)
- v0.2.18
- v0.2.19
- v0.2.20

**Comment by jean-christophe-manciot** [comment]
My bad: I mixed up vpcs with dynamips. Sorry about that. Nothing wrong with dynamips.
