### ISSUE TITLE
NetScaler is not booting

### ISSUE THREAD

**Issue by XemBryan** [GNS3/dynamips#95]
I'm using GNS3 2.1.12
NetScaler image is NSVPX-KVM-12.0-56.20_nc_32.qcow2
I'm using appliance as GNS3 VM, but it is booting forever and after hour or so it says disconnected in console.
Has anybody managed to boot NetScaler?
I'm on Win10

**Comment by grossmj** [comment]
Please post your question on https://gns3.com/community/latest, GitHub is only used for bug reports and discuss GNS3 development in general. Thank you.
