### ISSUE TITLE
Dynamips hypervisor process has stopped, return code: -11

### ISSUE THREAD

**Issue by arvinvelarde** [GNS3/dynamips#99]
Im using a Mac computer, when Im trying to save the configuration on c3725 I got the error

**Comment by grossmj** [comment]
What is the IOS image name you have used?

**Comment by arvinvelarde** [comment]
c3725-adventerprisek9-mz.123-11.T3.bin

**Comment by grossmj** [comment]
Some IOS images aren't well supported by Dynamips and can cause it to crash. 

We recommend using one of the following images: https://docs.gns3.com/1-kBrTplBltp9P3P-AigoMzlDO-ISyL1h3bYpOl5Q8mQ/index.html#h.hjaexffydx69

For instance c3725-adventerprisek9-mz.124-25d.bin or c3725-adventerprisek9-mz.124-15.T14.bin

**Comment by arvinvelarde** [comment]
thank you

**Comment by arvinvelarde** [comment]
Thank you very much for your help
